### ISSUE TITLE
Portrait に対応する

### ISSUE THREAD

**Issue by monry** [umm/canvas_resizer#13]
## What

* Portrait に対応する

## Why

* Gyzmo が Landscape を前提にしてしまっているので、Portrait もサポートする

## How

* https://github.com/umm-projects/canvas_resizer/blob/master/Assets/Scripts/UnityModule/CanvasResizer.cs#L211 の値を読み替えれば行ける？
* `#if UNITY_EDITOR` の中で `[SerializeField] private bool isPortrait = false;` とか書いておいて、それ参照すればヨサソウ

**Comment by fakestarbaby** [comment]
対応切実 :pray:
